# Generated by Django 4.2.2 on 2023-06-08 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('salt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodie',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='foodie',
            name='height',
        ),
        migrations.RemoveField(
            model_name='foodie',
            name='weight',
        ),
        migrations.AlterField(
            model_name='foodie',
            name='food',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
