# Generated by Django 4.2.2 on 2023-06-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0002_food_remove_foodie_calories_remove_foodie_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='total_calories',
            new_name='total_calory',
        ),
    ]
