# Generated by Django 4.2.2 on 2023-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0003_rename_total_calories_food_total_calory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
    ]
