# Generated by Django 4.2.2 on 2023-06-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0004_tracker_food_total_calories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
        migrations.RemoveField(
            model_name='food',
            name='total_calories',
        ),
    ]
